#!/bin/bash

echo "$@" | sed \
    -e "s/\(\(@\(red\|green\|yellow\|blue\|magenta\|cyan\|white\|reset\|b\|u\)\)\+\)[[]\{2\}\(.*\)[]]\{2\}/\1\4@reset/g" \
    -e "s/@red/$(tput setaf 1)/g" \
    -e "s/@green/$(tput setaf 2)/g" \
    -e "s/@yellow/$(tput setaf 3)/g" \
    -e "s/@blue/$(tput setaf 4)/g" \
    -e "s/@magenta/$(tput setaf 5)/g" \
    -e "s/@cyan/$(tput setaf 6)/g" \
    -e "s/@white/$(tput setaf 7)/g" \
    -e "s/@yellow_light/$(tput setaf 11)/g" \
    -e "s/@purple/$(tput setaf 13)/g" \
    -e "s/@orange/$(tput setaf 166)/g" \
    -e "s/@gray/$(tput setaf 243)/g" \
    -e "s/@pink/$(tput setaf 205)/g" \
    -e "s/@brown/$(tput setaf 130)/g" \
    -e "s/@turquoise/$(tput setaf 45)/g" \
    -e "s/@lavender/$(tput setaf 183)/g" \
    -e "s/@lime/$(tput setaf 190)/g" \
    -e "s/@teal/$(tput setaf 30)/g" \
    -e "s/@olive/$(tput setaf 64)/g" \
    -e "s/@maroon/$(tput setaf 88)/g" \
    -e "s/@navy/$(tput setaf 18)/g" \
    -e "s/@reset/$(tput sgr0)/g" \
    -e "s/@b/$(tput bold)/g" \
    -e "s/@u/$(tput sgr 0 1)/g"
