#!/bin/bash

echo "$@" | sed \
    -e "s/@red/$(tput setaf 1)/g" \
    -e "s/@green/$(tput setaf 2)/g" \
    -e "s/@yellow/$(tput setaf 3)/g" \
    -e "s/@blue/$(tput setaf 4)/g" \
    -e "s/@magenta/$(tput setaf 5)/g" \
    -e "s/@cyan/$(tput setaf 6)/g" \
    -e "s/@white/$(tput setaf 7)/g" \
    -e "s/@red_dark/$(tput setaf 88)/g" \
    -e "s/@green_dark/$(tput setaf 22)/g" \
    -e "s/@yellow_dark/$(tput setaf 58)/g" \
    -e "s/@blue_dark/$(tput setaf 19)/g" \
    -e "s/@magenta_dark/$(tput setaf 90)/g" \
    -e "s/@cyan_dark/$(tput setaf 23)/g" \
    -e "s/@white_dark/$(tput setaf 234)/g" \
    -e "s/@red_strong/$(tput setaf 9)/g" \
    -e "s/@green_strong/$(tput setaf 10)/g" \
    -e "s/@yellow_strong/$(tput setaf 11)/g" \
    -e "s/@blue_strong/$(tput setaf 12)/g" \
    -e "s/@magenta_strong/$(tput setaf 13)/g" \
    -e "s/@cyan_strong/$(tput setaf 14)/g" \
    -e "s/@white_strong/$(tput setaf 15)/g" \
    -e "s/@reset/$(tput sgr0)/g" \
    -e "s/@b/$(tput bold)/g" \
    -e "s/@u/$(tput sgr 0 1)/g"